version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '4321:4321'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: >
      sh -c "
        corepack enable &&
        corepack prepare pnpm@10.4.1 --activate &&
        find /home/node/app/node_modules -mindepth 1 -delete &&
        pnpm install &&
        pnpm dev
      "
    environment:
      NODE_ENV: development
      NODE_OPTIONS: '--max-old-space-size=4096 --no-deprecation'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-payload}
      POSTGRES_USER: ${POSTGRES_USER:-payload}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-payload}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-payload}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_modules:
